name: Ping Render Web Service

# This will run the job every 15 minutes
on:
  schedule:
    - cron: "*/14 * * * *"  # Runs every 14 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request to Render Service
        run: curl -I https://sppu-marksheet-analysis.onrender.com
